# Generated by Django 4.2.16 on 2024-11-26 11:26

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('space_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('currency', models.IntegerField(choices=[(0, '€'), (1, '£'), (2, '$')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_status', models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Paid')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('expense_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_lines', to='expense_app.expensespace')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('expense_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='expense_app.expensespace')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_status', models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Paid')], default=0)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_contributors', to='expense_app.contributor')),
                ('expense_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_contributions', to='expense_app.expenseline')),
            ],
        ),
    ]
