# Generated by Django 4.2.16 on 2024-11-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_remove_contribution_remaining_share_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='amount',
        ),
    ]
