# Generated by Django 4.2.16 on 2024-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_remove_contribution_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
