# Generated by Django 4.2.16 on 2024-12-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_alter_expenseline_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='paid_status',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='paid_status',
        ),
    ]
